language: python
python:
    - "2.7"
# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
# Before anything, see if we can get the mongoDB troubles out of the way.
    - sudo apt-get update
    - sudo apt-get --purge remove mongodb-10gen
    - sudo apt-get upgrade
    - yes | sudo apt-get -y install mongodb-clients mongodb-dev mongodb-server
# First, move code to correct place
    - mkdir -p ~/rosbuild_ws
    - cd ..; mv pr2_pbd ~/rosbuild_ws/
# Settings + Debug
    - export ROS_CI_DESKTOP=`lsb_release -cs`  # e.g. 'precise'
    - export ROS_CI_VERSION=groovy  # e.g. 'groovy'
    - export ROS_CI_PREFIX=ros-${ROS_CI_VERSION}-  # e.g. 'ros-groovy-'
# Exports for scripts
    - export ROS_HOSTNAME=localhost
    - export ROS_MASTER_URI=http://localhost:11311
    - export ROBOT=sim
# Add ROS repositories, setup keys, update
    - echo "deb http://packages.ros.org/ros/ubuntu $ROS_CI_DESKTOP main" | sudo tee /etc/apt/sources.list.d/ros-latest.list
    - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
    - sudo apt-get update
# Main installation, ROS setup
    - sudo apt-get install ${ROS_CI_PREFIX}desktop-full
    - sudo rosdep init
    - rosdep update
# Environment setup
    - source /opt/ros/${ROS_CI_VERSION}/setup.bash
# Add required PR2/desktop packages.
# (These can be compressed into one command, but this is easier to maintain.)
    - sudo apt-get -y install ${ROS_CI_PREFIX}simulator-gazebo
    - sudo apt-get -y install ${ROS_CI_PREFIX}openni-launch
    - sudo apt-get -y install ${ROS_CI_PREFIX}pr2-interactive-manipulation
    - sudo apt-get -y install ${ROS_CI_PREFIX}pr2-simulator
    - sudo apt-get -y install ${ROS_CI_PREFIX}pr2-desktop
    - sudo apt-get -y install python-rosinstall
# Add required python packages
    - cd ~/rosbuild_ws/pr2_pbd
    - pip install -r requirements.txt --use-mirrors
# Initialize ROS workspace, setup, set path
    - cd ~/rosbuild_ws
    - rosws init . /opt/ros/${ROS_CI_VERSION}
    - source ~/rosbuild_ws/setup.bash
    - export ROS_PACKAGE_PATH=~/rosbuild_ws/:/opt/ros/${ROS_CI_VERSION}/share:/opt/ros/${ROS_CI_VERSION}/stacks
# Make messages
    - cd pr2_pbd
    - rosmake
# Command to run tests
script:
    - rostest pr2_pbd_interaction test_endtoend.test
# NOTE(mbforbes): Change this to groovy-devel when moving to PR2 repo.
branches:
    only:
        - style
